version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm -g install serverless
  build:
    commands:
      - npm install
      - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - serverless